# Common packages to install
common_packages:
  - chrony
  - ntpdate
  - python3
  - python3-pip
  - vim

# Time sync settings
ntp_server: "pool.ntp.org" # automatically finds the best one for you
timezone: "America/Toronto"


# Slurm Configuration Variables

# Slurm User
slurm_user: "slurm"
slurm_group: "slurm"

# Cluster Settings
cluster_name: "proxbox-slurm"
control_node: "slurm-control-node-1"
auth_type: "munge"

# Slurm Node Configuration

# Controller Node
controller_ip: "192.168.200.201"
controller_hostname: "slurm-control-node-1"

# Worker Node
worker_ip: "192.168.201.201"
worker_hostname: "slurm-worker-node-1"


# Networking
slurmctld_port: 6817
slurmd_port: 6818
slurmctld_timeout: 120
slurmd_timeout: 300

# Directory Paths
slurm_config_dir: "/etc/slurm"
slurm_log_dir: "/var/log/slurm"
slurm_pid_dir: "/var/run"
slurm_spool_dir: "/var/spool/slurmd"
slurm_state_dir: "/var/spool/slurmctld"

# File Paths (based on directories)
slurmctld_log_file: "{{ slurm_log_dir }}/slurmctld.log"
slurmd_log_file: "{{ slurm_log_dir }}/slurmd.log"
slurm_job_log_file: "{{ slurm_log_dir }}/slurm-jobs.log"
slurmctld_pid_file: "{{ slurm_pid_dir }}/slurmctld.pid"
slurmd_pid_file: "{{ slurm_pid_dir }}/slurmd.pid"
slurm_conf_file: "{{ slurm_config_dir }}/slurm.conf"
# Job Completion
job_comp_type: "jobcomp/filetxt"
job_comp_loc: "/var/log/slurm-jobs.log"
min_job_age: 300

# Job Completion
job_comp_type: "jobcomp/filetxt"
job_comp_loc: "/var/log/slurm-jobs.log"
min_job_age: 300

# Scheduling
scheduler_type: "sched/backfill"
select_type: "select/cons_tres"

# Node Configuration
node_name: "slurm-worker-node-1"
node_cpus: 4

# Partition Configuration
partition_name: "debug"
partition_nodes: "ALL"
partition_default: "YES"
partition_max_time: "INFINITE"

