# Slurm Configuration Variables

# Slurm User
slurm_user: "slurm"

# Cluster Settings
cluster_name: "proxbox-slurm"
control_node: "slurm-control-node-1"
slurm_user: "slurm"
auth_type: "munge"

# Networking
slurmctld_port: 6817
slurmd_port: 6818
slurmctld_timeout: 120
slurmd_timeout: 300

# Directory Locations
state_save_location: "/var/spool/slurmctld"
slurmd_spool_dir: "/var/spool/slurmd"
slurmctld_log_file: "/var/log/slurmctld.log"
slurmd_log_file: "/var/log/slurmd.log"

# Job Completion
job_comp_type: "jobcomp/filetxt"
job_comp_loc: "/var/log/slurm-jobs.log"
min_job_age: 300

# Scheduling
scheduler_type: "sched/backfill"
select_type: "select/cons_tres"

# Node Configuration
node_name: "slurm-worker-node-[1-32]"
node_cpus: 2

# Partition Configuration
partition_name: "debug"
partition_nodes: "ALL"
partition_default: "YES"
partition_max_time: "INFINITE"

