- name: Install MUNGE on control node
  become: yes
  package:
    name:
      - munge
      - libmunge-dev
    state: present

- name: Ensure MUNGE directory exists
  become: yes
  file:
    path: /etc/munge
    state: directory
    owner: munge
    group: munge
    mode: '0700'

